name: Docker

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'backend/**'
      - 'frontend/**'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t emerald-plant-tracker:test .

      - name: Test development docker-compose build
        run: docker compose -f docker-compose.dev.yml build --no-cache 